spring.application.name=SmartHire
spring.datasource.url=jdbc:h2:mem:smarthire
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
jwt.secret=4r6G8s1h7K9vN2b5C6pQ8r3uV0xW2yZ7aT4eF1gH5jK6lM7nO8pQ9rS0tU1vW2x
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8086
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect